### ISSUE TITLE
SQLite lemma db and File lemma db cannot have some interface

### ISSUE THREAD

**Issue by nrfulton** [LS-Lab/KeYmaeraX-release#19]
The file lemma db allows arbitrary id's while the sqlite lemma db does not.

We should change the sqlite lemma DB to use `UNIQUE` ID's that aren't necessary auto-increment integers.

**Comment by aplatzer** [comment]
That means we should add a foreign key to the SQL table with the chosen identifier strings with a schema that says UNIQUE. Instead of or in addition to the auto-increment IDs?

Alternatively I wonder whether an improved version of the FileLemmaDB interface could work with existential types for LemmaID such that whatever is best can be used as identifiers. Albeit that might be a little annoying too. But certainly for micro-lemmas that merely store individual Provable steps, it's probably better to work with auto-incremented integer IDs, right @bbohrer ?

**Comment by smitsch** [comment]
No change needed. Both databases guarantee unique IDs: the file lemma DB checks user-provided IDs for uniqueness; the SQLite lemma DB does not accept external IDs. User-generated IDs are inconvenient in the SQLite lemma DB (which stores proof steps but not user lemmas).
