### ISSUE TITLE
[Usability enhancement] certain "permanent" hides fail while same formula is "temporarily hidden

### ISSUE THREAD

**Issue by rbohrer** [LS-Lab/KeYmaeraX-release#81]
To reproduce:

attempt to prove formula <x:=x;>x=x -> <x:=x;>x=x

implyR

"temporarily hide" the assumption
hideL(-1)

this generates the tactic hideL(-1) using "<x:=x;>x=x" which somehow seems to work.

Now do the same for the conclusion.

Error message: RepeatTactic failed on repetition 1

**Comment by bbohrer** [comment]
Update: 
We are now seeing a "loud failure" instead of a "silent failure," meaning that we get an error message if we run "hideL" on a "temporarily hidden" formula.

On the one hand, it is very obvious and understandable why the UI works this way, on the other hand, it was surprising/awkward to encounter. In particular, the issue came up a lot while working around Issue #86, so resolving #86 would make the current issue come up less often in practice.
